## optional arguments
#help: --outdir; default: default; The directory of the output file, default is same with the input file
outdir = default
#help: --frange; default: [0, inf]; Limit frequence range
frange = [0, inf]
#help: --nproc, -n; default: 1; number of process used in fitting baseline
nproc = 10
#help: --show_prog, --show-prog; default: True; choices: True, False; show progress bar
show_prog = True

## For FFT, smooth to find where should be replaced; for sin-fitting, preprocess.
#help: --s_method_t, --s-method-t; default: gaussian; choices: none, gaussian, boxcar, median; smooth method along time axis
s_method_t = gaussian
#help: --s_sigma_t, --s-sigma-t; default: 5; smooth sigma along time axis, size = (2*sigma+1) for boxcar and median
s_sigma_t = 5
#help: --s_method_freq, --s-method-freq; default: gaussian; choices: none, median, gaussian, boxcar; smooth method along freq axis
s_method_freq = gaussian
#help: --s_sigma_freq, --s-sigma-freq; default: 3; smooth sigma along freq axis, size = (2*sigma+1) for boxcar and median
s_sigma_freq = 3

## For FFT, smooth for finding Troughs of standing waves
#help: --s_method_t_T, --s-method-t-T; default: gaussian; choices: none, gaussian, boxcar, median; smooth method along time axis
s_method_t_T = gaussian
#help: --s_sigma_t_T, --s-sigma-t-T; default: 10; smooth sigma along time axis, size = (2*sigma+1) for boxcar and median
s_sigma_t_T = 10
#help: --s_method_freq_T, --s-method-freq-T; default: gaussian; choices: none, median, gaussian, boxcar; smooth method along freq axis
s_method_freq_T = gaussian
#help: --s_sigma_freq_T, --s-sigma-freq-T; default: 5; smooth sigma along freq axis, size = (2*sigma+1) for boxcar and median
s_sigma_freq_T = 5

## *select method used to fit standing wave
## ##########################################################################
#help: --method; default: sin_poly; choices: sin_poly, fft, running_median, running_mean; method to fit standing wave
method = fft
#help: --nobld; default: False; choices: True, False; if True, use the spectra before bld to subtract standing wave and output file name will add 'nobld'
nobld = False
#help: --fpattern_nobld, --fpattern-nobld; default: ;if not specify, guess from the History recored in the fpath
#fpattern_nobld = 

## *parameters for --method sin_poly
## ##########################################################################:
## addition options for preprocessing before fitting
#help: --njoin; default: 0; join nspec along t
njoin = 0

## sinusoidal standing wave (sw) fitting
#help: --exclude_m, --exclude-m; default: 0; 
exclude_m = 0
#help: --sin_f, --sin-f; default: 0.929; Initial guess for sw freq
sin_f = 0.929
#help: --bound_f, --bound-f; default: [0.9, 0.95]; Lower and upper bounds for sw freq
bound_f = [0.9, 0.95]
#help: --deg; default: 1; Degree of the added polynomial
deg = 1

## *parameters for --method fft
## ##########################################################################:
## replace big RFI or sources firstly
#help: --iter_twice, --iter-twice; default: True; choices: True, False; iterate twice? first remove the ripples and then back to find replace area again.
iter_twice = True
#help: --rfi_method, --rfi-method; default: near_ripple; choices: near_ripple, zero_ripple; method to replace big RFI, recommend the first one
rfi_method = near_ripple
#help: --mw_frange, --mw-frange; default: [0, 0]; milky way freq range. If do not use, keep it as default.
mw_frange = [0, 0]
#help: --rms_sigma, --rms-sigma; default: 6; gauss filter sigma to compute real rms
rms_sigma = 6
#help: --rms_frange, --rms-frange; default: [0, 0]; freq range to compute rms
rms_frange = [1405, 1410]
#help: --rms_step, --rms-step; default: 5; a step (MHz) to find where to compute real rms
rms_step = 5
#help: --times_thr, --times-thr; default: 4; sparks above ~ times of rms will be set noise (unsmooth)
times_thr = 4
#help: --times_s_thr, --times-s-thr; default: 3; above ~ times of rms will be replaced (smoothed once)
times_s_thr = 3
#help: --times_s_thr2, --times-s-thr2; default: 1.5; above ~ times of rms will be replaced (smoothed twice)
times_s_thr2 = 1.5
#help: --ext_freq, --ext-freq; default: 1.3; extend freq range to replace (mhz)
ext_freq = 1.3
#help: --rfi_width_lim, --rfi-width-lim; default: 30; rfi should contain more channels than limit
rfi_width_lim = 30
#help: --ext_sec, --ext-sec; default: 20; extend channel number of start and end of each section
ext_sec = 20
#help: --restrict_bound, --restrict-bound; default: False; choices: True, False; restrict replace area bound
restrict_bound = False
#help: --save_is_excluded, --save-is-excluded; default: False; choices: True, False; save the replaced area as is_excluded
save_is_excluded = False

## phase space
#help: --sw_base, --sw-base; default: True; choices: True, False; if True, remove constant components
sw_base = True
#help: --sw_periods, --sw-periods; default: ['1mhz', '2mhz', '0_04mhz']; choices: 1mhz, 2mhz, 0_04mhz, none; remove ripple (1mhz: 1.08mhz, 2mhz:1.92mhz, 0_04mhz: 0.039 mhz)
sw_periods = [1mhz, 2mhz, 0_04mhz]
#help: --check_2mhz, --check-2mhz; default: True; choices: True, False; if True, remove 2mhz from sw_periods except for Beam 6
check_2mhz = True
#help: --amp_thr_mean_factor, --amp-thr-mean-factor; default: [1.05, 1.4]; above mean amptitude threshold will be chosed, noise off and on
amp_thr_mean_factor = [1.05, 1.4]
#help: --amp_thr_solo_factor, --amp-thr-solo-factor; default: [1.4, 1.7]; above amptitude threshold will be chosed in every spec, noise off and on
amp_thr_solo_factor = [1.4, 1.7]
#help: --chan_wide, --chan-wide; default: 5; channel numbers near 1mhz to be chosed (wide)
chan_wide = 5
#help: --chan_narr, --chan-narr; default: 3; channel numbers near 1mhz to be chosed (narrow)
chan_narr = 3
#help: --choose_method, --choose-method; default: all; choices: all, interpolate; method to choose components in fft
choose_method = all
