## optional arguments
#help: --outdir; default: default; The directory of the output file, default is same with the input file
outdir = default
#help: --rms_frange; default: [0,0];freq range to compute rms, NEED TO DEFINE when sf, pdr 
rms_frange = [1405, 1410]
#help: --mw_frange; default: ;milky way freq range
mw_frange = [1420, 1423]
#help: --rms_sigma; default: 6; gauss filter sigma to compute real rms
rms_sigma = 6
#help: --all_beams default: False; choices: True, False; find time rfi after averaging all 19 beams
all_beams = False

## *Time domain continuous RFI
## ##########################################################################
#help: --tr, --time_rfi; default: False; choices: True, False; 
tr = False
#help: --tr_s_method_t; default: gaussian; smoothing method along time axis
tr_s_method_t = gaussian
#help: --tr_s_sigma_t; default: 10; 
tr_s_sigma_t = 10
#help: --tr_s_method_freq; default: gaussian; smoothing method along time freq
tr_s_method_freq = gaussian
#help: --tr_s_sigma_freq; default: 5; 
tr_s_sigma_freq = 5
#help: --tr_n_continue; default: 100; 
tr_n_continue = 100
#help: --tr_times; default: 6.0; 
tr_times = 6.0
#help: --tr_times_s; default: 1.5; 
tr_times_s = 1.5
#help: --ext_add; default: 0; extend rfi range
ext_add = 3
#help: --ext_frac; default: 0.0; between 0 and 1, extend rfi range
ext_frac = 0.0

## *Narrowband single channel RFI
## ##########################################################################
#help: --nr, --narr_rfi; default: False; choices: True, False; find long time narrow single channel rfi
nr = True
#help: --nr_mean_times; default: 100; first threhold, rfi is this times of median value after mean along time axis; \
nr_mean_times = 20
#help: --nr_diff_times; default: 30; second threhold, sharp edge on time axis. diff above this times of median will be recognized; \
nr_diff_times = 5
#help: --nr_mask_rms_times; default: 0; if == 0, mask whole channel; if > 0, mask RMS above ~ times of RMS.
nr_mask_rms_times = 5

## *Polarized RFI
## ##########################################################################
#help: --pr, --polar_rfi; default: False; choices: True, False; 
pr = False
#help: --pr_s_sigma; default: 5; gaussian smooth size for spectra smoothing along time axis
pr_s_sigma = 5
#help: --pr_times; default: 6; 
pr_times = 6
#help: --pr_times_s; default: 1; 
pr_times_s = 1.5

## *Long freq 
## ##########################################################################
#help: --lf, --long_freq; default: False; choices: True, False; find time rfi
lf = True
#help: --lsn_thr_type; default: input_med_times; choices: 'input_med_times','input_absmed_times','input_posimed_times'; \
#  input times of median value, its absolute value, or add an offset to make it positive. used for lf, sf, nr
lsn_thr_type = input_absmed_times
#help: --lf_frange; default: [1400, 1500];freq range exists long-freq time rfi
lf_frange = [1400, 1430]
#help: --lf_mean_times; default: 2; first threhold, rfi is this times of median value after mean along time axis; \
lf_mean_times = 5
#help: --lf_diff_times; default: 0; set 0 and do not change this parameter
lf_diff_times = 0
#help: --lf_rfi_last; default: [50, inf]; rfi lasts at least 20 spec numbers
lf_rfi_last = [30, inf]
#help: --lf_ext_add; default: 50; extend edge
lf_ext_add = 30
#help: --lf_mask_rms_times; default: -1; if == -1, mask whole spec; if == 0, only mask region in frange; \
#                   if > 0, mask RMS above ~ times of RMS. '
lf_mask_rms_times = -1

## *Short freq 
## ##########################################################################
#help: --sf, --short_freq; default: False; choices: True, False; find time rfi
sf = True
#help: --sf_use_time_only; default: False; choices: True, False; if true, only use 'is_timerfi' of 19 beams
sf_use_time_only = True                  
#help: --sf_frange; default: [1370, 1390];freq range exists short-freq time rfi
sf_frange = [1378, 1385]
#help: --sf_frange_step; default: ; if sf_frange is None and sf_file is None, cycle in whole freq band.
#sf_frange_step = 30
#help: --sf_file; default: ;freq range exists short-freq time rfi npy filename
#sf_file = 'RFI_franges.npy'
#help: --sf_mean_times; default: 3; first threhold, rfi is this times of median value after mean along time axis; \
sf_mean_times = 3
#help: --sf_diff_times; default: 1; second threhold, sharp edge on time axis. diff above this times of median will be recognized; \
sf_diff_times = .08
#help: --sf_rfi_last; default: [10, inf]; rfi lasts at least 10 spec numbers
sf_rfi_last = [20, inf]
#help: --sf_ext_add; default: 0; extend edge
sf_ext_add = 3
#help: --sf_mask_rms_times; default: 3; mask from peak to 2 sides, until RMS drops to 3 times of RMS
sf_mask_rms_times = 2
